gateway:
  apiExposedURL: "http://172.17.0.1:8000"
  webExposedURL: "http://172.17.0.1:8000"
  runserviceURL: "http://localhost:4000"
  configstoreURL: "http://localhost:4002"
  gitserverURL: "http://172.17.0.1:4003"

  web:
    listenAddress: ":8000"
  tokenSigning:
    # hmac or rsa (it possible use rsa)
    method: hmac
    # key to use when signing with hmac
    key: supersecretsigningkey
    # paths to the private and public keys in pem encoding when using rsa signing
    #privateKeyPath: /path/to/privatekey.pem
    #publicKeyPath: /path/to/public.pem
  adminToken: "admintoken"

scheduler:
  runserviceURL: "http://localhost:4000"

notification:
  webExposedURL: "http://172.17.0.1:8000"
  runserviceURL: "http://localhost:4000"
  configstoreURL: "http://localhost:4002"
  etcd:
    endpoints: "http://localhost:2379"

configstore:
  dataDir: /data/agola/configstore
  etcd:
    endpoints: "http://localhost:2379"
  objectStorage:
    type: posix
    path: /data/agola/configstore/ost
  web:
    listenAddress: ":4002"

runservice:
  #debug: true
  dataDir: /data/agola/runservice
  etcd:
    endpoints: "http://localhost:2379"
  objectStorage:
    type: posix
    path: /data/agola/runservice/ost
  web:
    listenAddress: ":4000"

executor:
  dataDir: /data/agola/executor
  # The directory containing the toolbox compiled for the various supported architectures
  toolboxPath: ./bin
  runserviceURL: "http://localhost:4000"
  web:
    listenAddress: ":4001"
  activeTasksLimit: 2
  driver:
    type: docker

gitserver:
  dataDir: /data/agola/gitserver
  gatewayURL: "http://localhost:8000"
  web:
    listenAddress: ":4003"